module commonMainProject {
	exports member.dao;
	exports reserve.dto;
	exports login.main;
	exports member.main;
	exports test.thread;
	exports movieJudge;
	exports pay.main;
	exports seat.dto;
	exports login.controller;
	exports login.user;
	exports common;
	exports pay.controller;
	exports commonMainProject;
	exports member.service;
	exports noticeBoard;
	exports login.url;
	exports login.service;
	exports idfind.controller;
	exports pay.dto;
	exports reserve.controller;
	exports reserve.main;
	exports member.controller;
	exports seat.controller;
	exports movieTest;
	exports login.dto;
	exports longin.idfind;
	exports member.dto;
	exports myInfo;
	exports login.dao;
	exports seat.main;
	exports myCGV;

	requires java.sql;
	requires javafx.base;
	requires javafx.controls;
	requires javafx.fxml;
	requires javafx.graphics;
}